### ISSUE TITLE
스타트업 검색 관련 이슈

### ISSUE THREAD

**Issue by WalkingWhale** [inhyeeeok/innohi_frontend-react#48]
- [x] 1. 서비스 상세에 있는 내용 검색해도 검색 안되는 현상 종종 발생
- [x] 2. 검색이 되었던 내용도 초기화 후 검색시 검색 안되는 현상 발생
- [x] 3. 검색 영역(기존 서비스 상세) 변경 필요

**Comment by inhyeeeok** [comment]
스타트업 검색 UI 변경 요청

**Comment by inhyeeeok** [comment]
진행중

**Comment by inhyeeeok** [comment]
데이터가 DynamoDB에 모두 입력되지 않아 커밋 보류 중

**Comment by inhyeeeok** [comment]
162건 데이터 insert 완료 예시



INSERT INTO startupArchiveDataTable value {'id':'', 'no':'158','name':'비주얼캠프','category_L':'에듀테크','category_S':'시선추적','service':'비대면 교육을 위한 시선추적기술','employeeNum':'15명','estbYear':2014,'investRound':'Series A','moneyRaised':'19억원','country':'대한민국','city':'경기도 분당구','logoLink':'https://image.rocketpunch.com/company/3849/visualcamp_logo_1527648585.jpg?s=400x400&t=inside'}
