### ISSUE TITLE
문의(설문) 접수 방식 변경 필요

### ISSUE THREAD

**Issue by WalkingWhale** [inhyeeeok/innohi_frontend-react#58]
현재 Google Form으로 접수되고있는 설문을 게시판형식으로 변경하는게 좋을것같다는 개선의견이 있었음(김은희 그룹장)

Google Form이 삽입되어 있는곳은 랜딩페이지의 1.일반문의(문의하기), 2.협업제안과 협의체공간의 3.스타트업 소싱 요청임

따라서 문의 작성(게시글 작성), 문의 조회(게시판), 답변(댓글 or 답글) 및 답변된 사항에 대해 사용자에게 알림 기능이 필요하리라 생각함

설문 구성

 1. 문의하기 - 문의 종류를 선택할수 있는 셀렉트 박스 + 텍스트 답변
 2. 협업제안 - 텍스트 답변 파일첨부기능
 3. 스타트업 소싱 요청 - 텍스트 답변

**Comment by inhyeeeok** [comment]
문의사항이 있어 답변 드립니다.

따라서 문의 작성(게시글 작성), 문의 조회(게시판), 답변(댓글 or 답글) 및 답변된 사항에 대해 **사용자에게 알림 기능**이 필요하리라 생각함

'사용자에게 알림 기능'에 대해 상세 설명 해주실수 있나요?

**Comment by inhyeeeok** [comment]
스타트업 소싱 요청 시 구글 폼을 걷어내고 고유의 폼으로 진행하기로 결정

**Comment by inhyeeeok** [comment]
벨리데이션 중 띄어쓰기 구별 필요
