### ISSUE TITLE
cognito 등록된 외부 이메일 로그인 처리 관련

### ISSUE THREAD

**Issue by WalkingWhale** [inhyeeeok/innohi_frontend-react#60]
1. cognito에 따로 등록된 외부 이메일 계정 로그인 가능하게 변경 필요(현재 불가능)

2. cognito에 따로 등록된 외부 이메일 계정으로 로그인 시도시 실패 alert가 계속 생기는 현상 있음

**Comment by inhyeeeok** [comment]
param.attributes.email_verified가 true 일 경우 등록된 아이디
false 일 경우 등록되지 않은 구글 SSO 로그인 아이디 구분

**Comment by inhyeeeok** [comment]
'cognito에 따로 등록된 외부 이메일 계정으로 로그인 시도 시 실패 alert가 계속 생기는 현상 있음'의 경우 AWS 콜백 문제로 인해 이슈가 있음. 해당 로직에 대해 검토 필요
