### ISSUE TITLE
(구)이노하이 페이지 접근시 리뉴얼된 이노하이 페이지로 리다이렉션 가능한지 검토 필요

### ISSUE THREAD

**Issue by WalkingWhale** [inhyeeeok/innohi_frontend-react#62]
구글 사이트 툴로 만들어진 (구)이노하이 페이지(https://sites.google.com/hist.co.kr/innohi/%ED%99%88) 접근시 리뉴얼된 이노하이 페이지(https://main.dxtribtwfr2oa.amplifyapp.com/)로 리다이렉션이 가능한지 기술 검토가 필요합니다.

**Comment by inhyeeeok** [comment]
https://sites.google.com/d/16pw9iXz3lEzzzMgSK9j6zypq3rDtqogw/p/1NpKaMVhSdWYekgownJdMfjeirQCARpxJ/edit

**Comment by inhyeeeok** [comment]
https://stackoverflow.com/questions/23239837/how-to-redirect-url-on-google-sites
