### ISSUE TITLE
스타트업 수요조사 현황 조회 개발

### ISSUE THREAD

**Issue by inhyeeeok** [inhyeeeok/innohi_frontend-react#66]

**Comment by WalkingWhale** [comment]
19일 테스트 사항 공유

신청서 작성 후 완료 메시지 alert 커스터마이징 필요해보임

신청서 목록 화면 신청분야 : 디지털 트랜스포메이션으로 고정되어 있음

**Comment by inhyeeeok** [comment]
신청서 작성 후 완료 메시지 alert 커스터마이징 필요해보임

**Comment by inhyeeeok** [comment]
날짜 포맷 변경 필요

**Comment by inhyeeeok** [comment]
권인혁 -> 한태준

1. 신청서 작성 후 완료 후 루틴 정의 필요
2. 단계 별 멘트 정리 필요 ex) 평가 위원회 날짜 확정 시 직접 연락드리겠습니다.

**Comment by WalkingWhale** [comment]
1. 신청서 작성 후 완료 후 루틴
제출 성공시 : 제출하기 버튼 클릭 -> validation check -> 정상 입력시 Alert창 팝업("신청이 완료되었습니다") -> 소싱 요쳥 현황 페이지로 이동
제출 실패시 : 제출하기 버튼 클릭 -> validation check -> 잘못입력된 부분으로 scroll up + alert message출력("xxx가 잘못입력되었습니다. 양식에 맞춰 입력바랍니다" / "xxx가 입력되지 않았습니다")

**Comment by inhyeeeok** [comment]
2. 단계 별 멘트 정리 항목

![image](https://user-images.githubusercontent.com/92982812/166343994-8a421a36-54b9-4a9f-adbc-1e9431eeca7b.png)

**Comment by WalkingWhale** [comment]
단계 별 멘트 정리 항목

신청단계 문구 - 단계별 이미지 상태
문구 순입니다

1. 신청서 검토 - image all deactive
담당자가 신청서를 확인하고 있습니다.

2. 신청서 접수 완료 - 소싱_신청_active
스타트업 발굴과 관련해 담당자가 연락드릴 예정입니다.

3. 스타트업 발굴 완료 - 스타트업발굴_active
평가위원회 개최 일자가 확정되면 연락드리겠습니다.

4. 스타트업 평가 완료 - 스타트업 선정_active
후속 업무에 관한 문의는 innohi@hist.co.kr로 연락 바랍니다.

5. 스타트업 소싱 완료 - 후속업무_active
스타트업 소싱이 완료되었습니다. 감사합니다.
