### ISSUE TITLE
220421 필요 추가 기능 및 개선사항 정리

### ISSUE THREAD

**Issue by WalkingWhale** [inhyeeeok/innohi_frontend-react#67]
1. 이벤트 페이지
- [x]  - 현재 이벤트 eventElement 파일 내에서 이벤트를 개별로 입력 / 수정 중 통합해 DB화 가능한지 검토 필요
- [x]  - 이벤트 페이지에 데이터 삽입시 메인페이지에도 동기화 되어 carousel에 표출되는 기능 필요함
- [x]  - 이벤트 입력시 시작일을 기준으로 자동 정렬이 필요해 보임
- [x]  - 이벤트 종료일 기준으로 이벤트가 끝나면 메인페이지에서 자동으로 내려오는 기능 필요함

2. 알려드려요 페이지
- [x]  - 통합 Json파일에 데이터를 보관 및 사용중이기 때문에 입력 / 수정시 번거로움 데이터 저장방식에 대한 개선이 필요해보임
- [x]  - 이벤트 페이지에 데이터 삽입시 협의체 공간 메인페이지에도 동기화 되어 carousel에 표출되는 기능 필요함

3. 이노하이 레터 페이지
- [x]  - 통합 Json파일에 데이터를 보관 및 사용중이기 때문에 입력 / 수정시 번거로움 데이터 저장방식에 대한 개선이 필요해보임
- [x]  - 이벤트 페이지에 데이터 삽입시 협의체 공간 메인페이지에도 동기화 되어 carousel에 표출되는 기능 필요함

**Comment by inhyeeeok** [comment]
1. 이벤트 페이지
현재 이벤트 eventElement 파일 내에서 이벤트를 개별로 입력 / 수정 중 통합해 DB화 가능한지 검토 필요
이벤트 페이지에 데이터 삽입시 메인페이지에도 동기화 되어 carousel에 표출되는 기능 필요함
이벤트 입력시 시작일을 기준으로 자동 정렬이 필요해 보임
이벤트 종료일 기준으로 이벤트가 끝나면 메인페이지에서 자동으로 내려오는 기능 필요함

우선 순위 산정 -> 진행 예정

**Comment by inhyeeeok** [comment]
1 예정 today() < startdate
2. 진행중 startdate <= today() <= enddate
3. 마감 endate < today()


![image](https://user-images.githubusercontent.com/92982812/166200027-0ea60c6d-5555-46a9-a0c2-2250cb144281.png)

**Comment by WalkingWhale** [comment]
1. 이벤트 페이지 - 메인페이지 관련

최대 표출 갯수 5개, 단 조건에 맞는 이벤트가 부족할 경우 적게 표출되거나 아예 표출되지 않아도 됨

조건 1. 현재 진행중인 이벤트
조건 2. 추후 진행 예정인 이벤트(today()에서 가장 날짜가 가까운 이벤트 순)

조건 1에 걸려서 이벤트 5개가 표출된다면 조건 2는 수행될 필요 없음
