### ISSUE TITLE
220510 이슈 사항 추가

### ISSUE THREAD

**Issue by WalkingWhale** [inhyeeeok/innohi_frontend-react#70]
insight 메뉴 - event

- [x] 이벤트 정렬기준 - 각 상태(진행,예정,마감)별 가장 빠른 날자부터 정렬되어야 하는데 마감 이벤트 중 정렬기준이 안맞는 이벤트가 있음 확인 필요

 
insight 메뉴 - innopick

- [x] 관리기능 없는 상태, 기능 추가 검토 필요
- [x] innopick 상세보기 이동시 URL에 파일명 찍히는 현상 수정 필요

**Comment by WalkingWhale** [comment]
innopick 상세보기 이동시 URL에 파일명 찍히는 현상 수정 필요

**Comment by inhyeeeok** [comment]
이벤트 정렬기준 - 각 상태(진행,예정,마감)별 가장 빠른 날자부터 정렬되어야 하는데 마감 이벤트 중 정렬기준이 안맞는 이벤트가 있음 확인 필요 
=> 순서 대로 정렬 했으나 Isotope 라이브러리가 제대로 그리지 못했음.
